name: Publish Contracts
on:
  push:
    branches: main
    paths:
      - "contracts/**"
      - ".github/workflows/contracts.yaml"

env:
  DATABASE_URL: mysql://constancy_fund:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/constancy_fund
  IPFS_INFURA_ID: ${{ secrets.IPFS_INFURA_ID }}
  IPFS_INFURA_SECRET: ${{ secrets.IPFS_INFURA_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: install
        run: npm install
      - name: build
        run: npx hardhat compile
      - name: test
        run: npx hardhat test
      - name: Deploy to IPFS
        run: npx ts-node scripts/deploy-smart-contract.ts
