name: Publish site
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "app/**"
      - "server/**"
      - ".github/workflows/main.yaml"

env:
  API_URL: https://api.constancy.fund
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_FRONTEND_API: clerk.constancy.fund
  CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
  CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
  DATABASE_URL: mysql://constancy_fund:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/constancy_fund
  EVERSIGN_API_KEY: ${{ secrets.EVERSIGN_API_KEY }}
  INFURA_ID: ${{ secrets.INFURA_ID }}
  IPFS_INFURA_ID: ${{ secrets.IPFS_INFURA_ID }}
  IPFS_INFURA_SECRET: ${{ secrets.IPFS_INFURA_SECRET }}
  IS_PRODUCTION: 1
  ORIGIN: https://constancy.fund
  STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  SUPPORT_EMAIL: support@constancy.fund

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Install NPM 8
        run: npm install -g npm@latest
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
